"""Tool functions exposed to TU Study Assistant agents."""

from crew.tools.moses_tools import (
    MOSES_MODULE_RESEARCH_TOOLS,
    MOSES_TOOLS,
    get_degree_area_modules,
    get_degree_program_structure,
    get_module_catalogs,
    get_module_details,
    search_degree_modules,
    search_degree_programs,
    search_modules,
)
from crew.tools.isis_tools import (
    CONFIRMATION_TOKEN,
    ISIS_READ_ONLY_TOOLS,
    ISIS_TOOLS,
    ISIS_WRITE_TOOLS,
    make_isis_read_only_tools,
)
from crew.tools.grademanager_tools import (
    GRADE_MANAGER_READ_TOOLS,
    GRADE_MANAGER_TOOLS,
    GRADE_MANAGER_WRITE_TOOLS,
    STUDY_ADVISOR_TOOLS,
    STUDY_PLAN_CONFIRMATION_TOKEN,
    add_module_to_study_plan,
    build_student_plan_context,
    check_module_against_study_plan,
    get_degree_requirement_details,
    get_study_plan_snapshot,
    list_study_plan_modules,
    remove_module_from_study_plan,
    run_study_plan_what_if,
    update_module_in_study_plan,
)
from crew.tools.grade_analysis_tools import (
    GRADE_ANALYSIS_TOOLS,
    GetDegreeGradeContributionBreakdownTool,
    GetGradeScenarioOutlookTool,
    RunGradeWhatIfScenarioTool,
    RunGradeSensitivityAnalysisTool,
    RunTargetGradeOptimizerTool,
    get_degree_grade_contribution_breakdown,
    get_grade_scenario_outlook,
    run_grade_what_if_scenario,
    run_grade_sensitivity_analysis,
    run_target_grade_optimizer,
)
from crew.tools.proposal_tools import (
    ProposeCourseActionsTool,
    ClearAllCourseProposalsTool,
    DeleteCourseProposalTool,
    collect_course_proposals,
    current_course_proposals,
)
from crew.tools.commitment_tools import (
    COURSE_COMMITMENT_EXECUTION_TOOLS,
    ExecuteApprovedCourseCommitmentsTool,
    ListApprovedCourseCommitmentActionsTool,
)
from crew.tools.degree_regulations_tools import (
    DEGREE_REGULATIONS_TOOLS,
    ExtractRegelstudienplanTableTool,
    ListDegreeRegulationPdfsTool,
    SearchDegreeRegulationPdfsTool,
)

COURSE_COMMITMENT_TOOLS = [
    ProposeCourseActionsTool(),
    ClearAllCourseProposalsTool(),
    DeleteCourseProposalTool(),
    ListApprovedCourseCommitmentActionsTool(),
    ExecuteApprovedCourseCommitmentsTool(),
]

__all__ = [
    "CONFIRMATION_TOKEN",
    "COURSE_COMMITMENT_TOOLS",
    "COURSE_COMMITMENT_EXECUTION_TOOLS",
    "DEGREE_REGULATIONS_TOOLS",
    "ISIS_READ_ONLY_TOOLS",
    "ISIS_TOOLS",
    "ISIS_WRITE_TOOLS",
    "GRADE_MANAGER_READ_TOOLS",
    "GRADE_ANALYSIS_TOOLS",
    "GRADE_MANAGER_TOOLS",
    "GRADE_MANAGER_WRITE_TOOLS",
    "MOSES_TOOLS",
    "MOSES_MODULE_RESEARCH_TOOLS",
    "STUDY_ADVISOR_TOOLS",
    "STUDY_PLAN_CONFIRMATION_TOKEN",
    "ExtractRegelstudienplanTableTool",
    "GetDegreeGradeContributionBreakdownTool",
    "GetGradeScenarioOutlookTool",
    "ListDegreeRegulationPdfsTool",
    "ProposeCourseActionsTool",
    "RunGradeWhatIfScenarioTool",
    "RunGradeSensitivityAnalysisTool",
    "RunTargetGradeOptimizerTool",
    "ClearAllCourseProposalsTool",
    "DeleteCourseProposalTool",
    "ListApprovedCourseCommitmentActionsTool",
    "ExecuteApprovedCourseCommitmentsTool",
    "SearchDegreeRegulationPdfsTool",
    "collect_course_proposals",
    "current_course_proposals",
    "make_isis_read_only_tools",
    "build_student_plan_context",
    "search_modules",
    "get_module_details",
    "get_module_catalogs",
    "search_degree_programs",
    "get_degree_program_structure",
    "get_degree_area_modules",
    "search_degree_modules",
    "get_study_plan_snapshot",
    "get_grade_scenario_outlook",
    "get_degree_grade_contribution_breakdown",
    "list_study_plan_modules",
    "get_degree_requirement_details",
    "check_module_against_study_plan",
    "run_grade_what_if_scenario",
    "run_grade_sensitivity_analysis",
    "run_target_grade_optimizer",
    "run_study_plan_what_if",
    "add_module_to_study_plan",
    "update_module_in_study_plan",
    "remove_module_from_study_plan",
]
